### ISSUE TITLE
[Suggestions] To-Do list

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/flippy#5]
Some suggestions in form of a to-do list:
- [ ] avoid the "zero" 0 for counting, I suggest to always start with number "1" for the first "flip-book page"
- [ ] Auto-generate a title image ("Deckblatt") with meta data like the filename and file creation date. Number should be "1", not "0" (zero).
- [ ] Add a framework for a web-based service (upload or side-load of a video, then processing and download possibility)
- [ ] https://github.com/ola-ct/flippy/issues/3 Let the user select the number of output images instead of the frame rate
- [ ] #6 option to crop and/or to zoom the video before the flip-book is created

**Comment by 607011** [comment]
Thanks for your suggestions.

I won't update this repository anymore, except for bugs. I'll leave it to the users to enhance the script.

**Comment by Wikinaut** [comment]
Good approach, thanks for your work.

And: I have further ideas for this c't section.

**Comment by Wikinaut** [comment]
add above: "\* [ ] Add a framework for a web-based service (upload or side-load of a video, then processing and download possibility)"
